# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-30 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '\u7ba1\u7406\u5458\u4fe1\u606f', 'verbose_name_plural': '\u7ba1\u7406\u5458\u4fe1\u606f'},
        ),
    ]
